import LeftSidebar from "@/components/LeftSidebar";
import ".././globals.css";
import RightSidebar from "@/components/RightSidebar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className=" flex justify-between max-w-8xl mx-auto">
          <div className="hidden sm:inline border-r sticky top-0">
            <LeftSidebar />
          </div>
          <div className=" w-2xl flex-1">{children} </div>
          <div className="lg:flex-col p-3 h-screen border-l hidden lg:flex w-[24rem]">
            <RightSidebar />
          </div>
        </div>
      </body>
    </html>
  );
}
